package com.wqm.myjz.dao;

import com.wqm.myjz.bean.Comment;
import com.wqm.myjz.bean.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_comment
     *
     * @mbg.generated Mon Jun 07 15:49:53 CST 2021
     */
    int updateByPrimaryKey(Comment record);
}